# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  imageRepo: bcs-app

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'bcs-registry-connection'
          repository: '$(imageRepo)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: latest
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'bcs-image'
          publishLocation: 'Container'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/s/deploy'
          artifact: 'manifest'
          publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to Dev Stage
  dependsOn: Build
  variables:
    acrSecret: passacr
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifest'
          targetPath: '$(Pipeline.Workspace)/manifest'
      - task: KubernetesManifest@1
        inputs:
          action: 'createSecret'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'bcs-kubernetes-connection'
          namespace: 'default'
          secretType: 'dockerRegistry'
          secretName: '$(acrSecret)'
          dockerRegistryEndpoint: 'bcs-registry-connection'
      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'bcs-kubernetes-connection'
          namespace: 'default'
          manifests: |
            $(Pipeline.Workspace)/manifest/deployment.yml
            $(Pipeline.Workspace)/manifest/service.yml